name: CI-Assignment
on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - 'main'
jobs:
  check_and_make_release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install deps
      run: sudo apt-get install build-essential make googletest google-mock libgtest-dev libgmock-dev 
    - name: build and run program
      run: make && make circular_queue_test
